export const REDIRECT_URI = process.env.EXPO_PUBLIC_REDIRECT_URI;
export const AUTH0_DOMAIN = process.env.EXPO_PUBLIC_AUTH0_DOMAIN;
export const AUTH0_CLIENT_ID = process.env.EXPO_PUBLIC_AUTH0_CLIENT_ID;
export const AUTH0_CLIENT_SECRET = process.env.EXPO_PUBLIC_AUTH0_CLIENT_SECRET;
export const AUTH0_AUDIENCE = process.env.EXPO_PUBLIC_AUTH0_AUDIENCE;
